# -*- coding: utf-8 -*-
"""LVADUSR160_Final Assessment_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ET2Z1dEX9Sl65cUG79bMCz6fWTCxhNT0
"""

import pandas as pd

df = pd.read_csv('/content/customer_segmentation.csv')

df.info()

df.isnull().sum()

df.bfill(inplace=True)

df.info()
df.isnull().sum()
df.fillna(method='bfill', inplace=True)

plt.figure(figsize=(12, 8))
plt.subplot(231)
plt.scatter(df['NumWebVisitsMonth'], df['MntMeatProducts'], s=32, alpha=0.8)
plt.title('NumWebVisitsMonth vs MntMeatProducts')

plt.subplot(232)
plt.scatter(df['NumWebVisitsMonth'], df['MntFishProducts'], s=32, alpha=0.8)
plt.title('NumWebVisitsMonth vs MntFishProducts')

plt.subplot(233)
plt.scatter(df['NumWebVisitsMonth'], df['MntSweetProducts'], s=32, alpha=0.8)
plt.title('NumWebVisitsMonth vs MntSweetProducts')

plt.subplot(234)
plt.scatter(df['NumWebVisitsMonth'], df['MntGoldProds'], s=32, alpha=0.8)
plt.title('NumWebVisitsMonth vs MntGoldProds')

plt.subplot(235)
plt.scatter(df['NumWebVisitsMonth'], df['NumDealsPurchases'], s=32, alpha=0.8)
plt.title('NumWebVisitsMonth vs NumDealsPurchases')

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
from sklearn.cluster import KMeans
x = df.values

wcss_list = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(df)
    wcss_list.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss_list)
plt.title('The Elbow Method Graph')
plt.xlabel('Number of clusters (k)')
plt.ylabel('WCSS (Within Cluster Sum of Squares)')
plt.show()

kmeans = KMeans(n_clusters=3, init='k-means++', random_state=42)
y_predict = kmeans.fit_predict(df)

cor = df.select_dtypes(include = ['float64','int64']).corr()

plt.figure(figsize=(8, 6))
plt.scatter(df['NumWebVisitsMonth'], df['MntMeatProducts'], c=y_predict, cmap='viridis', s=50)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s=200, c='red', label='Centroids')
plt.title('Clusters of Customers')
plt.xlabel('NumWebVisitsMonth')
plt.ylabel('MntMeatProducts')
plt.legend()
plt.show()

import seaborn as sns
sns.pairplot(df)
plt.show()

cor = df.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(cor, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=df)
plt.title('Boxplot of Features')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12, 6))
sns.violinplot(data=df, inner='quartile')
plt.title('Violin Plot of Features')
plt.xticks(rotation=45)
plt.show()

from sklearn.metrics import silhouette_score

silhouette_avg = silhouette_score(df, y_predict)
print("Silhouette Score:", silhouette_avg)