# -*- coding: utf-8 -*-
"""LVADSUSR160_KEERTHIK VISHAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXPP4RNLDx53fMfL7EzVrZ4as5QZXTfa
"""

#1)

length = input(print["Enter the length =",length])
width = input(print["Enter the width:",width])
area = length*width;
print("Area is",area)
if area>10000:
  print("Large")
elif area>5000 & area<10000:
  print("Medium")
else:
  print("Small");

#2)

#3)

#4)

#5)
int a;
for a>=100

#6)

#7)

#8)

#9)

#10)

#11)

#12)

#13)

#14)

#15)